version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8000
    container_name: manulifebe-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    restart: unless-stopped

networks:
  app-network:
    external: true